In [10]:
import pandas as pd
import numpy as np
import os
import weka.core.jvm
import pickle

import ucr
import uea

In [2]:
load_UEA_dataset = uea.load_UEA_dataset
load_UCR_dataset = ucr.load_UCR_dataset

# Inspect datasets

## UCR
Train size = 20, Test size = 342, Length = 24, Classes = 2. <br>
Each [[vector]] is one time series representing one day in this dataset, with 24 records. <br>
There are 20 examples in this dataset.

In [3]:
# Test behavior of os.path.join
os.path.join("C:\\", "Users", "Paws", "Desktop", "MasterProject", "ExtraDatasets", "UCRArchive_2018")

'C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\UCRArchive_2018'

### Chinatown dataset

In [13]:
train, train_labels, test, test_labels = load_UCR_dataset("C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\UCRArchive_2018", "Chinatown")
print(train.shape)
print('number of NAN: ', np.count_nonzero(np.isnan(train)))
train

(20, 1, 24)
number of NAN:  0


array([[[-0.07278082, -0.4609032 , -0.60595904, -0.78041809,
         -1.08817169, -1.12933619, -1.14697811, -1.1312964 ,
         -0.97447928, -0.91567286, -0.60203861,  0.00954817,
          1.20723894,  1.31505072,  1.19743787,  0.92300791,
          0.50156189,  0.95241112,  0.84067892,  0.71522522,
          0.26633621, -0.05709911, -0.39425592, -0.83922451]],

       [[-0.42365913, -0.67848696, -0.9215535 , -0.91371264,
         -0.9921212 , -1.14109747, -1.14109747, -1.14697811,
         -1.05876848, -0.89607072, -0.40993764,  0.07619545,
          1.1876368 ,  1.54635597,  1.25232387,  1.23468194,
          0.9778939 ,  1.0327799 ,  1.33269264,  1.0327799 ,
          0.35454584,  0.05463309, -0.02573568, -0.57655583]],

       [[-0.0139744 , -0.51382898, -0.85098579, -0.84902558,
         -1.1038534 , -1.13717704, -1.1175749 , -1.11365447,
         -0.99800185, -0.84314494, -0.40993764,  0.32710284,
          1.4385442 ,  1.88743321,  1.5639979 ,  1.24056258,
          1.040620

In [24]:
print(train_labels.shape)
train_labels

(20,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### DodgerLoopDay dataset - contains NAN
Other UCR datasets that contain missing values: DodgerLoopGame, DodgerLoopWeekend

In [10]:
train, train_labels, test, test_labels = load_UCR_dataset("C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\UCRArchive_2018", "DodgerLoopDay")
print(train.shape)
print('number of NAN: ', np.count_nonzero(np.isnan(train)))
print('position of NAN: ', np.argwhere(np.isnan(train)))
train

(78, 1, 288)
number of NAN:  236
position of NAN:  [[ 16   0  89]
 [ 16   0  90]
 [ 16   0 151]
 [ 16   0 152]
 [ 16   0 153]
 [ 16   0 154]
 [ 16   0 155]
 [ 16   0 156]
 [ 16   0 157]
 [ 16   0 158]
 [ 16   0 159]
 [ 16   0 160]
 [ 16   0 161]
 [ 16   0 162]
 [ 16   0 163]
 [ 16   0 164]
 [ 16   0 165]
 [ 16   0 166]
 [ 16   0 167]
 [ 16   0 168]
 [ 16   0 169]
 [ 16   0 170]
 [ 16   0 171]
 [ 16   0 172]
 [ 16   0 173]
 [ 16   0 174]
 [ 16   0 175]
 [ 17   0 162]
 [ 32   0 155]
 [ 32   0 156]
 [ 32   0 157]
 [ 32   0 158]
 [ 32   0 159]
 [ 32   0 160]
 [ 32   0 161]
 [ 32   0 162]
 [ 32   0 163]
 [ 32   0 164]
 [ 32   0 165]
 [ 32   0 166]
 [ 32   0 167]
 [ 32   0 168]
 [ 32   0 169]
 [ 32   0 170]
 [ 32   0 171]
 [ 32   0 172]
 [ 32   0 173]
 [ 32   0 174]
 [ 32   0 175]
 [ 32   0 176]
 [ 32   0 177]
 [ 32   0 178]
 [ 32   0 179]
 [ 32   0 180]
 [ 32   0 181]
 [ 32   0 182]
 [ 32   0 183]
 [ 32   0 184]
 [ 32   0 185]
 [ 32   0 186]
 [ 32   0 187]
 [ 32   0 188]
 [ 32   0 189]
 [ 3

array([[[12., 18., 11., ...,  6.,  3.,  6.]],

       [[12.,  9., 11., ..., 10.,  4.,  9.]],

       [[ 8.,  5., 10., ...,  7.,  8.,  6.]],

       ...,

       [[11., 10.,  8., ..., 14.,  9., 13.]],

       [[ 9.,  4.,  3., ..., 14.,  9., 11.]],

       [[16., 11.,  5., ..., 16., 21.,  6.]]])

In [12]:
train[16,0]

array([ 7.,  5.,  5.,  5.,  0.,  5.,  1.,  7.,  7.,  2.,  1.,  2.,  2.,
        4.,  1.,  4.,  2.,  3.,  3.,  4.,  2.,  6.,  3.,  3.,  1.,  2.,
        1.,  4.,  0.,  1.,  2.,  2.,  1.,  2.,  0.,  5.,  1.,  1.,  1.,
        2.,  2.,  3.,  3.,  0.,  4.,  2.,  3.,  3.,  5.,  0.,  3.,  5.,
        1.,  2.,  1.,  2.,  6.,  5.,  6., 10.,  8.,  7.,  8., 12.,  1.,
        7.,  7., 11., 11., 12.,  8., 14., 13., 15., 16., 11., 18., 17.,
       24., 21., 22., 27., 29., 22., 23., 27., 39., 38., 41., nan, nan,
       45., 34., 51., 44., 43., 31., 37., 43., 29., 33., 43., 33., 40.,
       35., 40., 44., 45., 45., 46., 35., 24., 36., 37., 34., 31., 40.,
       27., 39., 24., 27., 47., 25., 24., 30., 26., 23., 27., 33., 25.,
       29., 26., 27., 29., 13., 24., 26., 25., 33., 19., 28., 20., 20.,
       23., 12., 18., 21., 22., 29., 30., 27., nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, 34., 32., 42., 37., 33

In [9]:
print(train_labels.shape)
train_labels

(78,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

### Earthquakes dataset

In [16]:
train, train_labels, test, test_labels = load_UCR_dataset("C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\UCRArchive_2018", "Earthquakes")
print(train.shape)
print('number of NAN: ', np.count_nonzero(np.isnan(train)))
train

(322, 1, 512)
number of NAN:  0


array([[[-0.51800895, -0.51800895,  2.6542109 , ..., -0.51800895,
          1.4658264 , -0.51800895]],

       [[ 1.9437326 , -0.35311462, -0.35311462, ..., -0.35311462,
         -0.35311462, -0.35311462]],

       [[ 2.6385165 , -0.31610235, -0.31610235, ..., -0.31610235,
         -0.31610235, -0.31610235]],

       ...,

       [[-0.26465174, -0.26465174, -0.26465174, ..., -0.26465174,
         -0.26465174, -0.26465174]],

       [[-0.49082731, -0.49082731, -0.49082731, ..., -0.49082731,
         -0.49082731, -0.49082731]],

       [[-0.4839215 , -0.4839215 , -0.4839215 , ..., -0.4839215 ,
         -0.4839215 , -0.4839215 ]]])

In [6]:
print(train_labels.shape)
train_labels

(322,)


array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,

## UEA datasets
Train size = 108, Test size = 72, Length = 1197, Classes = 12 <br>
Each [[vector]] is one feature of one time series representing, with 1197 records. <br>
Each matrix is one example, and there are 108 examples in the train set.

### Cricket dataset

In [3]:
train, train_labels, test, test_labels = load_UEA_dataset("C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\Multivariate_arff", "Cricket")
    
print(train.shape)
print('number of NAN: ', np.count_nonzero(np.isnan(train)))
train

DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['C:\\Users\\Paws\\Anaconda3\\envs\\python3_8\\Lib\\site-packages\\javabridge\\jars\\rhino-1.7R4.jar', 'C:\\Users\\Paws\\Anaconda3\\envs\\python3_8\\Lib\\site-packages\\javabridge\\jars\\runnablequeue.jar', 'C:\\Users\\Paws\\Anaconda3\\envs\\python3_8\\Lib\\site-packages\\javabridge\\jars\\cpython.jar', 'C:\\Users\\Paws\\Anaconda3\\envs\\python3_8\\lib\\site-packages\\weka\\lib\\python-weka-wrapper.jar', 'C:\\Users\\Paws\\Anaconda3\\envs\\python3_8\\lib\\site-packages\\weka\\lib\\weka.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support disabled


(108, 6, 1197)
number of NAN:  0


array([[[-0.97251624, -0.95808021, -0.95941077, ..., -0.96385263,
         -0.97251624, -0.97251624],
        [-0.23086643, -0.23086643, -0.23086643, ..., -0.30275647,
         -0.30275647, -0.30275647],
        [-0.46882568, -0.44001364, -0.45153846, ..., -0.41696402,
         -0.38238958, -0.38238958],
        [-0.57753142, -0.76006771, -0.801435  , ..., -0.91096077,
         -0.91096077, -0.91096077],
        [ 0.30005524,  0.31732246,  0.33112823, ...,  0.51267408,
          0.51267408,  0.51267408],
        [-0.44176442, -0.40152762, -0.39347425, ..., -0.67715273,
         -0.67715273, -0.67715273]],

       [[-0.55939365, -0.57637074, -0.57467003, ..., -0.55403141,
         -0.55939365, -0.55939365],
        [ 0.1300044 ,  0.14903235,  0.14141917, ...,  0.18708825,
          0.18708825,  0.18708825],
        [-0.99353478, -0.95156726, -0.93120876, ..., -0.25381589,
         -0.25381589, -0.25381589],
        [-0.24153099, -0.38239986, -0.41057164, ..., -0.4528293 ,
         -0.45

print(train_labels.shape)
train_labels

### Heartbeat dataset

In [4]:
train, train_labels, test, test_labels = load_UEA_dataset("C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\Multivariate_arff", "Heartbeat")
    
print(train.shape)
print('number of NAN: ', np.count_nonzero(np.isnan(train)))
train

INFO:weka.core.jvm:JVM already running, call jvm.stop() first


(204, 61, 405)
number of NAN:  0


array([[[-2.40448779e-01, -2.13011299e-01, -2.72773083e-01, ...,
         -2.47829919e-01, -2.47269971e-01, -2.18050836e-01],
        [-2.58528968e-01, -2.65621208e-01, -2.99644791e-01, ...,
         -2.54887007e-01, -3.02855467e-01, -2.79853609e-01],
        [-2.70630954e-01, -2.22924964e-01, -2.00883588e-01, ...,
         -2.42593980e-01, -2.77791166e-01, -2.71709299e-01],
        ...,
        [-4.75327850e-01, -4.40281060e-01, -3.92227505e-01, ...,
         -2.86803092e-01, -1.86882702e-01, -1.77783897e-01],
        [-5.43324650e-01, -4.95981969e-01, -4.58760994e-01, ...,
         -3.30366817e-01, -3.33857281e-01, -3.63765511e-01],
        [-4.10560305e-01, -3.94560246e-01, -5.11960367e-01, ...,
         -4.38221127e-01, -5.29640558e-01, -5.16961951e-01]],

       [[ 7.42770014e-01,  5.77788802e-01,  1.93164553e-02, ...,
         -1.46876946e-02,  1.37414700e-01,  1.10588073e-01],
        [ 1.00618991e+00,  1.44935906e+00,  1.32126746e+00, ...,
          4.40200417e-01,  9.41662019e

In [6]:
print(train_labels.shape)
train_labels

(204,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [21]:
train, train_labels, test, test_labels = load_UEA_dataset("C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\Multivariate_arff", "InsectWingbeat")
    
print(train.shape)
print('number of NAN: ', np.count_nonzero(np.isnan(train)))

INFO:weka.core.jvm:JVM already running, call jvm.stop() first


JavaException: GC overhead limit exceeded

In [6]:
print(train_labels.shape)
train_labels

(204,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

## Check the number of NAN values in each dataset
Note NAN can either be:
- missing values
- varying column length

### NAN in UCR

In [4]:
datasetPath = "C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\UCRArchive_2018"

keys = []
values =[]
for filename in os.listdir(datasetPath):
    if filename == "Missing_value_and_variable_length_datasets_adjusted":
        continue
    
    train, train_labels, test, test_labels = load_UCR_dataset(datasetPath, filename)
    #number of missing values in each dataset
    num_NAN = np.count_nonzero(np.isnan(train))
    if num_NAN != 0:
        index_NAN = np.argwhere(np.isnan(train))
        keys.append(filename)
        values.append(index_NAN)
        print(filename, num_NAN)
        
UCR_NAN_dict = dict(zip(keys,values))


#Pickle the dictionary containing indexes of NAN values
pickle.dump(UCR_NAN_dict, open('../ExtraDatasets/NAN_info/UCR_NAN_dict.pth','wb'))


#To unpickle, use the following code format
#pickle.load(open(file_path,'rb'))
#open(file_path,'rb').close()
# 
# UCR_NAN_dict = pickle.load(open('../ExtraDatasets/NAN_info/UCR_NAN_dict.pth','rb'))
# open('../ExtraDatasets/NAN_info/UCR_NAN_dict.pth','rb').close()

AllGestureWiimoteX 112527
AllGestureWiimoteY 111412
AllGestureWiimoteZ 112339
DodgerLoopDay 236
DodgerLoopGame 65
DodgerLoopWeekend 38
GestureMidAirD1 40257
GestureMidAirD2 40257
GestureMidAirD3 40257
GesturePebbleZ1 29210
GesturePebbleZ2 33800
MelbournePedestrian 82
PickupGestureWiimoteZ 10756
PLAID 547870
ShakeGestureWiimoteZ 10656


In [23]:
UCR_NAN_dict["MelbournePedestrian"]

array([[ 122,    0,    2],
       [ 214,    0,    3],
       [ 227,    0,    3],
       [ 232,    0,    4],
       [ 240,    0,    4],
       [ 247,    0,    9],
       [ 247,    0,   10],
       [ 264,    0,    4],
       [ 282,    0,    4],
       [ 286,    0,    3],
       [ 286,    0,    4],
       [ 286,    0,   16],
       [ 292,    0,    4],
       [ 295,    0,    3],
       [ 302,    0,    4],
       [ 311,    0,    4],
       [ 313,    0,    4],
       [ 350,    0,    2],
       [ 350,    0,    4],
       [ 358,    0,    3],
       [ 562,    0,   16],
       [ 638,    0,   16],
       [ 700,    0,    4],
       [ 779,    0,    2],
       [ 840,    0,    1],
       [ 866,    0,    3],
       [ 869,    0,    3],
       [ 874,    0,    1],
       [ 879,    0,    1],
       [ 895,    0,    4],
       [ 902,    0,    3],
       [ 910,    0,    2],
       [ 910,    0,    3],
       [ 914,    0,    0],
       [ 914,    0,    1],
       [ 914,    0,    2],
       [ 914,    0,    3],
 

### NAN in UEA

In [20]:
datasetPath = "C:\\Users\\Paws\\Desktop\\MasterProject\\ExtraDatasets\\Multivariate_arff"

# keys = []
# values =[]
for i, filename in enumerate(os.listdir(datasetPath)):
    if filename == "DataDimensions.csv" or filename == "Descriptions" or filename == "Images":
        continue
    elif i < 17:
        continue
        
    train, train_labels, test, test_labels = load_UEA_dataset(datasetPath, filename)
    #number of missing values in each dataset
    num_NAN = np.count_nonzero(np.isnan(train))
    if num_NAN != 0:
        index_NAN = np.argwhere(np.isnan(train))
        keys.append(filename)
        values.append(index_NAN)
        print(filename, num_NAN)

UEA_NAN_dict = dict(zip(keys,values))


#Pickle the dictionary containing indexes of NAN values
pickle.dump(UEA_NAN_dict, open('../ExtraDatasets/NAN_info/UEA_NAN_dict.pth','wb'))


#To unpickle, use the following code format
#pickle.load(open(file_path,'rb'))
#open(file_path,'rb').close()
# 
# UCR_NAN_dict = pickle.load(open('../ExtraDatasets/NAN_info/UEA_NAN_dict.pth','rb'))
# open('../ExtraDatasets/NAN_info/UEA_NAN_dict.pth','rb').close()

INFO:weka.core.jvm:JVM already running, call jvm.stop() first


JavaException: GC overhead limit exceeded

In [19]:
keys, values

(['CharacterTrajectories'],
 [array([[   0,    0,    0],
         [   0,    0,    1],
         [   0,    0,    2],
         ...,
         [1421,    2,  179],
         [1421,    2,  180],
         [1421,    2,  181]], dtype=int64)])

In [17]:
for i, filename in enumerate(os.listdir(datasetPath)):
    if filename == "DataDimensions.csv" or filename == "Descriptions" or filename == "Images":
        continue
    print(i,filename)

0 ArticularyWordRecognition
1 AtrialFibrillation
2 BasicMotions
3 CharacterTrajectories
4 Cricket
7 DuckDuckGeese
8 EigenWorms
9 Epilepsy
10 ERing
11 EthanolConcentration
12 FaceDetection
13 FingerMovements
14 HandMovementDirection
15 Handwriting
16 Heartbeat
18 InsectWingbeat
19 JapaneseVowels
20 Libras
21 LSST
22 MotorImagery
23 NATOPS
24 PEMS-SF
25 PenDigits
26 PhonemeSpectra
27 RacketSports
28 SelfRegulationSCP1
29 SelfRegulationSCP2
30 SpokenArabicDigits
31 StandWalkJump
32 UWaveGestureLibrary


# Stop JVM after done with load_UEA_dataset() function
Otherwise, restarting the python kernel is needed to start JVM.

In [22]:
weka.core.jvm.stop()